micronaut:
  application:
    name: natalie
netty:
  default:
    allocator:
      max-order: 3
nats.addresses:
- nats://localhost:4222
mongodb.uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/mydb
